import { useEffect } from 'react'
import { INLINE_VIEWS, PANEL_VIEWS, SUMMARY_VIEWS, VIEWS_META } from '../lib/views'
import type { ViewKey } from '../lib/views'
import { RUN_SUMMARY_TONE } from '../lib/runStatus'
import { CloseIcon } from './icons'
import { Button } from './Button'
import { Badge } from './Badge'
import { NewRunForm } from '../../features/runs/NewRunForm'
import { AgentsPanel } from '../../features/agents/AgentsPanel'
import { PipelinesPanel } from '../../features/pipelines/PipelinesPanel'
import { MemoryPanelContent } from '../../features/memory/MemoryPanel'
import { HealthPanelContent } from '../../features/health/HealthPanel'
import { PromptPanelContent } from '../../features/prompts/PromptPanel'
import { SettingsPanelContent } from '../../features/settings/SettingsPanel'
import { GitPanelContent } from '../../features/git/GitPanel'
import { useRunsStore } from '../../stores/runsStore'
import { shortId } from '../../features/trajectories/shortId'
import type { Run } from '../lib/types'

// ─── SidebarHost (T3) ─────────────────────────────────────────────────────
// Sub-sidebar 260px (spec ade-shell-visual §3): abre à direita do rail quando
// activeView !== null. Duas formas de conteúdo:
//   - LEVES (INLINE_VIEWS): conteúdo real da view (NewRunForm p/ prompt;
//     demais = componente existente extraído, sem wrapper de Drawer).
//   - PESADAS (SUMMARY_VIEWS): resumo + botão "Open panel" (onExpand) que
//     abre o drawer completo da view.
// Header padrão §6 (36px): título (VIEWS_META) + ações à direita. Esc fecha
// (mesmo padrão do Drawer). Uma sidebar por vez (viewStore já garante).

export interface SidebarHostProps {
  active: ViewKey | null
  onClose: () => void
  onExpand: () => void
}

// Descrição curta das views pesadas (corpo do resumo — sem query; o painel
// completo carrega os dados). runs tem resumo dinâmico do runsStore.
const SUMMARY_DESC: Partial<Record<ViewKey, string>> = {
  agents: 'Agent inventory and runtime details for the workspace.',
  pipelines: 'Pipeline templates and the visual pipeline studio.',
  artifacts: 'Files and artifacts generated by the AI in the active run workspace.',
  terminal: 'Interactive web terminal for the active run workspace.',
  ast: 'AST tree and dependency map for the run codebase.',
  coverage: 'Test coverage report and metrics for the run.',
  docker: 'Docker environments and devcontainer export.',
  mcp: 'MCP playground — servers, tools and calls.',
  evals: 'Run summaries, benchmarks and leaderboard.',
  trajectories: 'Fork, export, import and per-run timeline.',
}

export function SidebarHost({ active, onClose, onExpand }: SidebarHostProps) {
  const runs = useRunsStore((s) => s.runs)
  const activeRunId = useRunsStore((s) => s.activeRunId)
  const selectRun = useRunsStore((s) => s.selectRun)

  // Esc fecha (padrão Drawer): listener global enquanto a sidebar está aberta.
  useEffect(() => {
    if (!active) return
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose()
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [active, onClose])

  if (!active) return null

  const label = VIEWS_META[active].label
  const isInline = INLINE_VIEWS.includes(active)
  const isSummary = SUMMARY_VIEWS.includes(active)
  // Só exibe "Open panel" quando a view TEM drawer (PANEL_VIEWS). runs é
  // resumo interativo; agents/pipelines ainda não têm painel — sem affordance
  // morta nem hint órfão (fix round 1, F1/F2).
  const canExpand = isSummary && PANEL_VIEWS.includes(active)

  // Mesmo wire de onCreated do RunsWorkspace (padrão upsert+select no store).
  const handleCreated = (run: Run) => {
    useRunsStore.getState().upsertRun(run)
    useRunsStore.getState().selectRun(run.id)
  }

  let content: React.ReactNode = null
  if (isInline) {
    switch (active) {
      case 'prompt':
        content = <NewRunForm onCreated={handleCreated} narrow />
        break
      case 'agents':
        content = <AgentsPanel />
        break
      case 'pipelines':
        content = <PipelinesPanel />
        break
      case 'memory':
        content = <MemoryPanelContent />
        break
      case 'health':
        content = <HealthPanelContent />
        break
      case 'prompts':
        content = <PromptPanelContent />
        break
      case 'settings':
        content = <SettingsPanelContent />
        break
      case 'git':
        content = <GitPanelContent runId={activeRunId ?? ''} />
        break
    }
  } else if (active === 'runs') {
    content = <RunsSummary runs={runs} activeRunId={activeRunId} onSelect={selectRun} />
  } else {
    content = (
      <p className="text-xs leading-relaxed text-[var(--text-dim)]">
        {SUMMARY_DESC[active]}
        {canExpand && <span className="mt-1.5 block text-[var(--text-dim)]/70">Open panel for the full view.</span>}
      </p>
    )
  }

  return (
    <aside
      aria-label={label}
      className="flex w-[var(--sidebar-w)] shrink-0 flex-col border-r border-[var(--border)] bg-[var(--bg-elev)]"
    >
      {/* Header padrão (spec §6): 36px, título + ações direita. */}
      <header className="flex h-[var(--panel-head-h)] shrink-0 items-center justify-between gap-2 border-b border-[var(--border)] px-3">
        <h2 className="min-w-0 truncate text-sm font-semibold text-[var(--text)]">{label}</h2>
        <div className="flex shrink-0 items-center gap-1">
          {canExpand && (
            <Button size="sm" variant="subtle" onClick={onExpand} aria-label={`Open ${label} panel`}>
              Open panel
            </Button>
          )}
          <button
            type="button"
            aria-label={`Close ${label}`}
            onClick={onClose}
            className="flex h-6 w-6 items-center justify-center rounded text-[var(--text-dim)] transition-colors duration-[var(--dur-fast)] hover:bg-[var(--bg-elev-2)] hover:text-[var(--text)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent)]"
          >
            <CloseIcon />
          </button>
        </div>
      </header>
      {/* Corpo: scroll interno com gutter estável (padrão Drawer). */}
      <div className="min-h-0 flex-1 overflow-y-auto p-3 [scrollbar-gutter:stable]">{content}</div>
    </aside>
  )
}

// Resumo de runs (barato — lê o store): lista compacta com seleção direta.
// O botão "Open panel" (header) permanece como affordance; runs não tem
// drawer próprio nesta fase.
// Tone reduzido do resumo (ok p/ running/completed, accent p/ queued/pending)
// vive em RUN_SUMMARY_TONE (runStatus.ts — fonte única de status de RUN).

function RunsSummary({
  runs,
  activeRunId,
  onSelect,
}: {
  runs: Run[]
  activeRunId: string | null
  onSelect: (id: string) => void
}) {
  if (runs.length === 0) {
    return <p className="text-xs text-[var(--text-dim)]">No runs yet — create one from the Prompt view.</p>
  }
  return (
    <ul className="space-y-1.5">
      {runs.map((run) => {
        const active = run.id === activeRunId
        const tone = RUN_SUMMARY_TONE[run.status] ?? 'accent'
        return (
          <li key={run.id}>
            <button
              type="button"
              aria-pressed={active}
              onClick={() => onSelect(run.id)}
              className={[
                'w-full rounded-md border border-[var(--border)] bg-[var(--bg)] px-2.5 py-1.5 text-left transition-colors duration-[var(--dur-fast)] hover:border-[var(--border-hover)] hover:bg-[var(--bg-elev-2)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent)]',
                active ? 'border-[var(--accent)]' : '',
              ].join(' ')}
            >
              <span className="flex items-center justify-between gap-2">
                <span className="truncate font-mono text-xs text-[var(--text)]">{shortId(run.id)}</span>
                <Badge tone={tone}>{run.status}</Badge>
              </span>
              <span className="mt-0.5 block truncate text-xs text-[var(--text-dim)]">{run.idea || '—'}</span>
            </button>
          </li>
        )
      })}
    </ul>
  )
}
